// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3n-ydH4BWtSs9UoU8sWPt5n3tVQIqso',
    appId: '1:894261560341:web:48e1d9db1257353e32fa1c',
    messagingSenderId: '894261560341',
    projectId: 'newsapp-1f276',
    authDomain: 'newsapp-1f276.firebaseapp.com',
    storageBucket: 'newsapp-1f276.appspot.com',
    measurementId: 'G-F4SPSN5T3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRLDIZD960pyWw4GVV8HPUEvlbXZZnzw',
    appId: '1:894261560341:android:c28b6c76c423ee6332fa1c',
    messagingSenderId: '894261560341',
    projectId: 'newsapp-1f276',
    storageBucket: 'newsapp-1f276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUExYNaBFuPRL_AOlkwN0W-_otOX_XtkM',
    appId: '1:894261560341:ios:2b01ecffa7f4b61832fa1c',
    messagingSenderId: '894261560341',
    projectId: 'newsapp-1f276',
    storageBucket: 'newsapp-1f276.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUExYNaBFuPRL_AOlkwN0W-_otOX_XtkM',
    appId: '1:894261560341:ios:2b01ecffa7f4b61832fa1c',
    messagingSenderId: '894261560341',
    projectId: 'newsapp-1f276',
    storageBucket: 'newsapp-1f276.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );
}
